#!/bin/sh

cat <<EOF
Warning: this is not the pstop binary!

As of v0.5, and due to a possible naming conflict, pstop has been
renamed to ps-top and ps-stats is a separate binary.
This change required me to move the build locations to a different directory.

Also please adjust your github.com repo reference to https://github.com/sjmudd/ps-top.git

Install each binary by doing:
go get -u github.com/sjmudd/ps-top/cmd/ps-top
go get -u github.com/sjmudd/ps-top/cmd/ps-stats

Sorry for the confusion.
EOF
