#!/bin/sh

set -e

# figure out how we were called
dirname=$(dirname $0)
# Make sure we have the version of Go we want to depend on, either from the
# system or one we grab ourselves.
. $dirname/ensure-go-installed

# Since we want to be able to build this outside of GOPATH, we set it
# up so it points back to us and go is none the wiser

set -x
rm -rf .gopath
mkdir -p .gopath/src/github.com/sjmudd
ln -s "$PWD" .gopath/src/github.com/sjmudd/ps-top
export GOPATH=$PWD/.gopath:$GOPATH
