#!/bin/bash

set -e

dirname=$(dirname $0)

. $dirname/bootstrap

mkdir -p bin
bindir="$PWD"/bin
scriptdir="$PWD"/script

version=$(git rev-parse HEAD)
describe=$(git describe --tags --always --dirty)

export GOPATH="$PWD/.gopath"
cd .gopath/src/github.com/sjmudd/ps-top ||\
	exit 1

# build the binaries
go build cmd/ps-top/ps-top.go
go build cmd/ps-stats/ps-stats.go
